# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-12-28 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=100)),
                ('product_cost', models.IntegerField()),
                ('product_class', models.CharField(max_length=20)),
                ('no_of_product', models.IntegerField()),
                ('manufacture_date', models.DateField(max_length=100)),
                ('expiry_date', models.DateField(max_length=100)),
                ('customer_name', models.CharField(max_length=100)),
                ('mobile', models.BigIntegerField()),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
    ]
